### ISSUE TITLE
CMake install writes into source directory

### ISSUE THREAD

**Issue by aradi** [rk-lindsey/chimes_calculator#1]
# Issue

During the installation when using the CMake build system, the source folder is overwritten with the compiled libraries and executables. This is very contrary to the CMake philosophy of not changing anything in the source folder. Also, it makes integration into other CMake projects impossible as the libraries can not be installed properly.

# How to reproduce
```
  mkdir _build
  cmake -DDEBUG=0 ..
 make install
```

# Expected behavior

Installation of the libraries into the folders determined by `CMAKE_INSTALL_PREFIX`.

# Observed behavior

Binaries are written directly into the source folder.

**Comment by rk-lindsey** [comment]
I've committed edits which should resolve this issue. Users now have the option to compile with a `CMAKE_INSTALL_PREFIX` flag, i.e.:

`mkdir _build`
`cd _build`
`cmake -DDEBUG=0 -DCMAKE_INSTALL_PREFIX=/my/path ..`
`make`
`make install`

If `CMAKE_INSTALL_PREFIX` is not specified, executables etc. generated via cmake will remain in the `_build` directory.

Please let me know if this solution resolves the issues satisfactorily.
