### ISSUE TITLE
C interface does not handle multiple ChIMES instances

### ISSUE THREAD

**Issue by aradi** [rk-lindsey/chimes_calculator#31]
# Problem

The current C-interface does not provide a method to destroy a ChIMES instance. This inevitable leads to memory holes, if any application wishes to initialize ChIMES calculators multiple times, even if only one instance is used at a time. (Consequently, the Fortran interface stops if such an attempt is made.)

This would happen, if DFTB+ is used as a library, and instances of DFTB+ are created and destroyed several times.

# Solution

Provide a routine in the C-interface, which can deallocate/destroy the global ChIMES instance.

**Comment by aradi** [comment]
Looking more to the code in detail, one may get away without the finalizer in the C-inteface.

Question: Is it memory-hole safe to call `set_chimes_serial` and `init_chimes_serial` several times with different data? If yes, I'd lift the restriction in the Fortran interface, which only allows to create one instance of the ChIMES calculator during entire run-time of a program...

**Comment by nirgoldman** [comment]
We have determined that the current versions of the APIs are memory-hole safe. In addition, a new PR has just been submitted that provides wrapper functions to allow for multiple ChIMES instances in Fortran and C to be created. This is includes routines that can create and destroy these instances. Backwards compatibility with the previous APIs (with global ChIMES instance only) has been maintained.
