### ISSUE TITLE
Segfault on specific parametrization file

### ISSUE THREAD

**Issue by aradi** [rk-lindsey/chimes_calculator#50]
# Description

The calculator crashes when reading the attached parameterization file. According to my information, it was generated by the chimes_lsq tool excluding the H-H interaction.

# How to reproduce

Compile chimes_calculator v1.0.2 and run
```
./chimescalc-test_serial-C params.txt test.xyz.txt 1
```
the program starts, but segfaults when reading in the parameterization file.

# Expected behavior

Smooth processing of the file with or a well defined error message.

[params.txt](https://github.com/rk-lindsey/chimes_calculator/files/10929731/params.txt)
[test.xyz.txt](https://github.com/rk-lindsey/chimes_calculator/files/10929732/test.xyz.txt)

**Comment by nirgoldman** [comment]
The issue with these example files appears to be fully resolved. Thanks.

**Comment by aradi** [comment]
Cool, thanks for the fix. We plan to release the next DFTB+ version in about 2 month from now, till then, it would be cool to have a tagged release of the chimes_calculator and a corresponding new package on Conda, so that we can rely upon it as dependency. Thanks in advance!
