### ISSUE TITLE
OOM errors when use ChIMES calculator Python serial interface multiple times

### ISSUE THREAD

**Issue by shihkual** [rk-lindsey/chimes_calculator#67]
I'm using the Python serial interface to calculate energy, forces, and stress to simulate a system. The job ran on the University of Michigan's Greatlakes CPU node single core. When the function **`chimescalc_serial_py.calculate_chimes`** was called by roughly 2000~3000 times, the error code was reported as an out-of-memory error. Here, I provided the minimal codes to produce the error code. The codes need to be adjusted are the module path name in `test_chimes.py`, and the parameters in `slurm` which is the slurm script.

**Comment by shihkual** [comment]
[bug.tar.gz](https://github.com/rk-lindsey/chimes_calculator/files/15172934/bug.tar.gz)

**Comment by rk-lindsey** [comment]
This issue was resolved by commit #69
